### ISSUE TITLE
Volunteer

### ISSUE THREAD

**Issue by easyforgood** [gdgbeijing/gdghub#10]
大家好 我叫Sip 刚毕业入职了北京的公司，从事分布式后台的工作，但是喜欢研究前端和前沿的技术。

认识gdg是因为之前我们学校的老师参与创办了苏州gdg然后带我们参加了一次活动。

然后参加了几次gdg活动后，开始喜欢上了这种社区，觉得和别人分享交流有新技术或者技术实践，是一件非常有趣而且非常非常有意义的事情，因为可以普及技术、推动技术的发展并帮助到很多需要技术解决问题的人，所以很希望自己可以参与到创办和组织这种技术社区活动的过程中来。然而之前在苏州待的时间不长就离开了，没有能够参与过，所以希望能够把握到这次机会！！

然后作为志愿者，我除了能提供体力劳动（Volunteer）以外，我还会使用golang python nodejs的语言，大前端除了ios都做过点东西。另外 photoshop也会，以前参与学生会为活动做海报（**designer属性**）。同时担任过部长组织过校内科技活动，也具有一定组织协调能力（**event属性**）。担任过班级团支书和党支部宣传委员，经常会写这种新闻稿、报告之类的东西（**article属性**，感谢我党）。能力比较杂深度有限但是非常非常希望帮助到gdg@beijing社区(*•̀ᴗ•́ *)و ̑̑﻿。

email: siplexy.pi@outlook.com
Wechat: easysiplexy
Telegram: [@siporange](https://t.me/siporange)
twitter: [@Siplexy](https://twitter.com/Siplexy) 求互fo (/ω＼)

> BTW, 没有权限选择 label

**Comment by hanguokai** [comment]
欢迎加入 🎉
