### ISSUE TITLE
北京 GDG DevFest 2017 开始筹备

### ISSUE THREAD

**Issue by hanguokai** [gdgbeijing/gdghub#11]
详细信息见 https://github.com/gdgbeijing/devfest2017 。愿意参与的志愿者请关注 devfest2017 项目。

活动结束后关闭此 issue 。

**Comment by hanguokai** [comment]
北京 DevFest 2017 前期筹备已经完成，活动即将对外发布。愿意参与本次活动志愿者工作的请和活动负责人袁滚滚联系。

**Comment by muzi131313** [comment]
@hanguokai 嗨，这次的gdg的ppt有整理么？

**Comment by hanguokai** [comment]
@muzi131313 已在官网公布 http://devfest2017.gdgbeijing.org/
视频回放：http://www.itdks.com/eventlist/detail/1627
PPT 下载：https://pan.baidu.com/s/1eShHLXg

**Comment by muzi131313** [comment]
感谢，感谢

李彦风
