### ISSUE TITLE
volunteer

### ISSUE THREAD

**Issue by polimao** [gdgbeijing/gdghub#14]
PHP 后端开发工程师，热爱前沿技术！喜欢 Google 文化。希望成为一名志愿者，为社区伙伴们做贡献。

**Comment by hanguokai** [comment]
@yepolite 你好，请问怎样和你联系？先加入到志愿者的微信群吧。

**Comment by polimao** [comment]
我的联系方式: ヽ(=^･ω･^=)丿
我的微信号正是 github 用户名 yepolite
或者手机号 13269276128

**Comment by hanguokai** [comment]
欢迎！
