### ISSUE TITLE
volunteer

### ISSUE THREAD

**Issue by yanchao92** [gdgbeijing/gdghub#2]
Hi all
  我叫闫超，25岁，目前在百度公司做产品经理。
  大学时候学习的是软件工程专业，所以上学时便对于google的各项产品很感兴趣，经常一个人刷android各种版本，使用谷歌的工具搭梯子翻墙。
  由于工作的原因，所以对新鲜事物很感兴趣，喜欢追踪一些科技相关的热点新闻和报道，例如google 眼镜，无人驾驶等等；平时也喜欢探索一些未知的东西，例如一个人去非英语母语国家，如泰国、俄罗斯旅行。我希望加入这个活动能让我认识到更多的朋友，了解到更多更好玩的东西。
我的微信是 18811727164 
真心希望加入这个团体，谢谢！

**Comment by hanguokai** [comment]
欢迎闫超 :tada:
