### ISSUE TITLE
volunteer

### ISSUE THREAD

**Issue by lysh001** [gdgbeijing/gdghub#21]
我想要加入gdg志愿者，
姓名：李燚
参加过10+场gdg活动
想要成为DevFest北京志愿者，望批准
手机13651235051
邮箱2731461992@qq.com

**Comment by hanguokai** [comment]
欢迎~

北京 DevFest 2017 前期筹备已经完成，活动即将对外发布。愿意参与本次活动志愿者工作的请和活动负责人袁滚滚联系。
