### ISSUE TITLE
volunteer 

### ISSUE THREAD

**Issue by ichbinlinda** [gdgbeijing/gdghub#24]
#volunteer
您好，我是一名在艺术行业做app渠道运营的技术爱好者，目前在自行学习编程等相关信息；因一直喜爱google的理念，且先前曾在北京哥伦比亚中心参加过Google的活动，收获颇多，机缘巧合下，了解到gdgbj在招志愿者，希望能贡献一点力量。我曾在14-18年期间在大学内参与过10多次线下志愿者活动，也是无国界爱心教育外联的志愿者，因此具有丰富的志愿者活动经验，希望有机会可以参与，多谢🙏

**Comment by hanguokai** [comment]
已联系
