### ISSUE TITLE
申请成为摄影师或自愿者

### ISSUE THREAD

**Issue by Steven-Yao** [gdgbeijing/gdghub#26]
辛苦管理员打标签~~

**Comment by hanguokai** [comment]
把你的个人简介、联系方式发给我吧 han.guokai [at] gmail 。下次有活动的时候叫上你。

**Comment by Steven-Yao** [comment]
> 把你的个人简介、联系方式发给我吧 han.guokai [at] gmail 。下次有活动的时候叫上你。

好的，谢谢~
