### ISSUE TITLE
Volunteer

### ISSUE THREAD

**Issue by Petterpx** [gdgbeijing/gdghub#27]
Hi, 我是来自北京海淀的 Android Developer，工作两年, 平时热衷于技术分享与记录，想参与到社区做志愿者，和大家做一些有意思的事。
Name : 史艺辉(Petterp)
Email : ShiyihuiCloud@163.com
微信 ：Petterpx

**Comment by hanguokai** [comment]
欢迎参与社区明年的活动 👏
