### ISSUE TITLE
Volunteer

### ISSUE THREAD

**Issue by zhenghetian** [gdgbeijing/gdghub#3]
各位好
     想加入GDG。

     我是田正赫，目前从事产品经理，之前干过Android开发，本科专业是软件工程。
     对消费电子比较关注，从HTC G1起使用接触Android系统，平常也是Google全家桶的用户。
  
   希望能加入GDG社区，增长见识、结交同好，为社区发展贡献一份力量。

     比较擅长于组织、协调（大学组织了不少活动）活动。

一般双休时间都方便（只要不加班）。

希望加入。谢谢

我的微信是：tianzhenghe，手机是：15210032789。 #2

**Comment by hanguokai** [comment]
欢迎加入 🎉
