### ISSUE TITLE
Volunteer

### ISSUE THREAD

**Issue by myrao** [gdgbeijing/gdghub#8]
Androider 一枚，两年前刚学 Android 的时候参加了 GDG Beijing 举办的一次线下分享会后就一直关注了 GDG Beijing。现趁这个机会期望能够加入 GDG 的自愿者（QAQ 其实我内心是想分享的，无奈技术还没到境界 :) ）。
Mail：raomengyang@gmail.com

**Comment by hanguokai** [comment]
欢迎加入 🎉
